### ISSUE TITLE
Can you add web.config?

### ISSUE THREAD

**Issue by aarongustafson** [maxmcd/taut#2]
We had an issue deploying the site. Check out the default Node web.config template here: https://a-k-apart.com/webconfigs/web.config.node.txt

Ping me when it’s in and we can try again.

**Comment by maxmcd** [comment]
Hey @aarongustafson, added web.config. I tried hosting this application on Azure and for some reason the iisnode module just seems to be serving the `./dist/index.js` file to the browser. http://taut.azurewebsites.net/

Any idea what's going on here? My search for good web resources has come up short.

**Comment by maxmcd** [comment]
Figured it out. The site now runs on azure without a web.config. Using the azure-cli `site create` process is sufficient. Hopefully that's enough?

Seems the issue was that I was not allowing azure to pass a `port` env variable, along with some windows specific issues. So likely I could include a working site.config if needed.

**Comment by aarongustafson** [comment]
I will try deploying today
